apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls
  namespace: meus-apps
spec:
  secretName: app-tls
  issuerRef:
    name: letsencrypt-nginx
    kind: ClusterIssuer
  dnsNames:
    - oondemand.online
    - api.meus-apps.oondemand.online
