apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls
  namespace: meus-apps-homolog
spec:
  secretName: app-tls
  issuerRef:
    name: letsencrypt-nginx
    kind: ClusterIssuer
  dnsNames:
    - homolog.app1.central.oondemand.online
    - homolog.api.app1.central.oondemand.online
