apiVersion: v1
kind: Service
metadata:
  name: meus-apps-backend-homolog-service
  namespace: meus-apps-homolog
spec:
  type: NodePort
  selector:
    app: meus-apps-backend-homolog
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
