name: Deploy meus-apps-backend

on:
  push:
    branches:
      - homolog

jobs:
  build_and_publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: write # Permissão para o workflow criar tags

    steps:
      - uses: actions/checkout@v3

      - name: Config git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Instalar dependências
        run: npm ci

      - name: Criar release com release-it
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Obter tag da release
        id: extract_tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Construir e publicar imagem
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.GH_PAT }} ghcr.io
          docker build -f ./infra/docker/Dockerfile.prod --build-arg SERVICE_VERSION=${{ env.TAG }} --tag ghcr.io/oondemand/meus-apps-backend:${{ env.TAG }}-homolog .
          docker push ghcr.io/oondemand/meus-apps-backend:${{ env.TAG }}-homolog

      - name: Criar kubeconfig
        run: |
          mkdir -p "${HOME}/.kube"
          curl -s -H "Authorization: Bearer ${{secrets.DO_ACCESS_TOKEN_HOMOLOG}}" "${{secrets.DO_CLUSTER_AUTHENTICATION_URL_HOMOLOG}}" > "$HOME/.kube/config"

      - name: Usar contexto do cluster
        run: |
          kubectl config use-context ${{ secrets.CLUSTER_HOMOLOG }}

      - name: 🚀 Substituir variáveis no deployment-homolog.yml e aplicar no cluster
        run: |
          envsubst < infra/kubernetes/deployment-homolog.yaml | kubectl apply -f -

        env:
          IMAGE_TAG: ${{ env.TAG }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
          PORT: ${{ secrets.PORT }}
          DB_SERVER: ${{ secrets.DB_SERVER_HOMOLOG }}
          DB_USER: ${{ secrets.DB_USER_HOMOLOG }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD_HOMOLOG }}
          DB_NAME: ${{ secrets.DB_NAME_HOMOLOG }}
          DB_AUTH_SOURCE: ${{ secrets.DB_AUTH_SOURCE }}
          DB_REPLICA_SET: ${{ secrets.DB_REPLICA_SET_HOMOLOG }}
          DB_TSL: ${{ secrets.DB_TSL_HOMOLOG }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          BASE_CLIENT_URL: ${{ secrets.BASE_CLIENT_URL_HOMOLOG }}
